/** Generated from the pinned headers. Pointer and size arguments use bigint. */
export interface LowLevelFunctions {
  adetail_image(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<number>;
  convert(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: bigint, arg5: number): Promise<number>;
  convert_with_components(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: number, arg8: bigint, arg9: number, arg10: number): Promise<number>;
  disable_imatrix_collection(): Promise<void>;
  enable_imatrix_collection(): Promise<void>;
  free_adetailer_ctx(arg0: bigint): Promise<void>;
  free_sd_audio(arg0: bigint): Promise<void>;
  free_sd_ctx(arg0: bigint): Promise<void>;
  free_sd_images(arg0: bigint, arg1: number): Promise<void>;
  free_upscaler_ctx(arg0: bigint): Promise<void>;
  generate_image(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  generate_video(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint): Promise<number>;
  get_upscale_factor(arg0: bigint): Promise<number>;
  load_imatrix(arg0: bigint): Promise<number>;
  new_adetailer_ctx(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<bigint>;
  new_sd_ctx(arg0: bigint): Promise<bigint>;
  new_upscaler_ctx(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: bigint, arg5: bigint): Promise<bigint>;
  preprocess_canny(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): Promise<number>;
  save_imatrix(arg0: bigint): Promise<void>;
  sd_cache_params_init(arg0: bigint): Promise<void>;
  sd_cancel_generation(arg0: bigint, arg1: number): Promise<void>;
  sd_commit(): Promise<bigint>;
  sd_ctx_has_control_net(arg0: bigint): Promise<number>;
  sd_ctx_load_control_net(arg0: bigint, arg1: bigint): Promise<number>;
  sd_ctx_params_init(arg0: bigint): Promise<void>;
  sd_ctx_params_to_str(arg0: bigint): Promise<bigint>;
  sd_ctx_supports_image_generation(arg0: bigint): Promise<number>;
  sd_ctx_supports_video_generation(arg0: bigint): Promise<number>;
  sd_ctx_unload_control_net(arg0: bigint): Promise<number>;
  sd_get_default_sample_method(arg0: bigint): Promise<number>;
  sd_get_default_scheduler(arg0: bigint, arg1: number): Promise<number>;
  sd_get_model_version_name(arg0: bigint): Promise<bigint>;
  sd_get_num_physical_cores(): Promise<number>;
  sd_get_system_info(): Promise<bigint>;
  sd_hires_params_init(arg0: bigint): Promise<void>;
  sd_hires_upscaler_name(arg0: number): Promise<bigint>;
  sd_img_gen_params_init(arg0: bigint): Promise<void>;
  sd_img_gen_params_to_str(arg0: bigint): Promise<bigint>;
  sd_list_devices(arg0: bigint, arg1: bigint): Promise<bigint>;
  sd_lora_apply_mode_name(arg0: number): Promise<bigint>;
  sd_prediction_name(arg0: number): Promise<bigint>;
  sd_preview_name(arg0: number): Promise<bigint>;
  sd_rng_type_name(arg0: number): Promise<bigint>;
  sd_sample_method_name(arg0: number): Promise<bigint>;
  sd_sample_params_init(arg0: bigint): Promise<void>;
  sd_sample_params_to_str(arg0: bigint): Promise<bigint>;
  sd_scheduler_name(arg0: number): Promise<bigint>;
  sd_set_backend_eval_callback(arg0: bigint, arg1: bigint): Promise<void>;
  sd_set_log_callback(arg0: bigint, arg1: bigint): Promise<void>;
  sd_set_preview_callback(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number, arg5: bigint): Promise<void>;
  sd_set_progress_callback(arg0: bigint, arg1: bigint): Promise<void>;
  sd_type_name(arg0: number): Promise<bigint>;
  sd_version(): Promise<bigint>;
  sd_vid_gen_params_init(arg0: bigint): Promise<void>;
  str_to_lora_apply_mode(arg0: bigint): Promise<number>;
  str_to_prediction(arg0: bigint): Promise<number>;
  str_to_preview(arg0: bigint): Promise<number>;
  str_to_rng_type(arg0: bigint): Promise<number>;
  str_to_sample_method(arg0: bigint): Promise<number>;
  str_to_scheduler(arg0: bigint): Promise<number>;
  str_to_sd_hires_upscaler(arg0: bigint): Promise<number>;
  str_to_sd_type(arg0: bigint): Promise<number>;
  upscale(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: bigint): Promise<number>;
}
