/** Generated from the pinned headers. Pointer and size arguments use bigint. */
export interface LowLevelFunctions {
  ggml_backend_alloc_buffer(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_alloc_ctx_tensors(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_alloc_ctx_tensors_from_buft(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_alloc_ctx_tensors_from_buft_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_buffer_clear(arg0: bigint, arg1: number): Promise<void>;
  ggml_backend_buffer_free(arg0: bigint): Promise<void>;
  ggml_backend_buffer_get_alignment(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_alloc_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_buffer_get_base(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_max_size(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_size(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_type(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_get_usage(arg0: bigint): Promise<number>;
  ggml_backend_buffer_init_tensor(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_buffer_is_host(arg0: bigint): Promise<number>;
  ggml_backend_buffer_name(arg0: bigint): Promise<bigint>;
  ggml_backend_buffer_reset(arg0: bigint): Promise<void>;
  ggml_backend_buffer_set_usage(arg0: bigint, arg1: number): Promise<void>;
  ggml_backend_buft_alloc_buffer(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_buft_get_alignment(arg0: bigint): Promise<bigint>;
  ggml_backend_buft_get_alloc_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_buft_get_device(arg0: bigint): Promise<bigint>;
  ggml_backend_buft_get_max_size(arg0: bigint): Promise<bigint>;
  ggml_backend_buft_is_host(arg0: bigint): Promise<number>;
  ggml_backend_buft_name(arg0: bigint): Promise<bigint>;
  ggml_backend_compare_graph_backend(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<number>;
  ggml_backend_cpu_buffer_from_ptr(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_cpu_buffer_type(): Promise<bigint>;
  ggml_backend_cpu_init(): Promise<bigint>;
  ggml_backend_cpu_reg(): Promise<bigint>;
  ggml_backend_cpu_set_abort_callback(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_backend_cpu_set_n_threads(arg0: bigint, arg1: number): Promise<void>;
  ggml_backend_cpu_set_threadpool(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_cpu_set_use_ref(arg0: bigint, arg1: number): Promise<void>;
  ggml_backend_dev_backend_reg(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_buffer_from_host_ptr(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_backend_dev_buffer_type(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_by_name(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_by_type(arg0: number): Promise<bigint>;
  ggml_backend_dev_count(): Promise<bigint>;
  ggml_backend_dev_description(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_get(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_get_props(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_dev_host_buffer_type(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_init(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_dev_memory(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_backend_dev_name(arg0: bigint): Promise<bigint>;
  ggml_backend_dev_offload_op(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_dev_supports_buft(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_dev_supports_op(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_dev_type(arg0: bigint): Promise<number>;
  ggml_backend_device_register(arg0: bigint): Promise<void>;
  ggml_backend_event_free(arg0: bigint): Promise<void>;
  ggml_backend_event_new(arg0: bigint): Promise<bigint>;
  ggml_backend_event_record(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_event_synchronize(arg0: bigint): Promise<void>;
  ggml_backend_event_wait(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_free(arg0: bigint): Promise<void>;
  ggml_backend_get_alignment(arg0: bigint): Promise<bigint>;
  ggml_backend_get_default_buffer_type(arg0: bigint): Promise<bigint>;
  ggml_backend_get_device(arg0: bigint): Promise<bigint>;
  ggml_backend_get_max_size(arg0: bigint): Promise<bigint>;
  ggml_backend_graph_compute(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_graph_compute_async(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_graph_copy(out: bigint, arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_graph_copy_free(arg0: bigint): Promise<void>;
  ggml_backend_graph_plan_compute(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_graph_plan_create(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_graph_plan_free(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_guid(arg0: bigint): Promise<bigint>;
  ggml_backend_init_best(): Promise<bigint>;
  ggml_backend_init_by_name(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_init_by_type(arg0: number, arg1: bigint): Promise<bigint>;
  ggml_backend_is_cpu(arg0: bigint): Promise<number>;
  ggml_backend_load(arg0: bigint): Promise<bigint>;
  ggml_backend_load_all(): Promise<void>;
  ggml_backend_load_all_from_path(arg0: bigint): Promise<void>;
  ggml_backend_meta_device(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  ggml_backend_meta_split_axis_name(arg0: number): Promise<bigint>;
  ggml_backend_name(arg0: bigint): Promise<bigint>;
  ggml_backend_offload_op(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_reg_by_name(arg0: bigint): Promise<bigint>;
  ggml_backend_reg_count(): Promise<bigint>;
  ggml_backend_reg_dev_count(arg0: bigint): Promise<bigint>;
  ggml_backend_reg_dev_get(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_reg_get(arg0: bigint): Promise<bigint>;
  ggml_backend_reg_get_proc_address(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_reg_name(arg0: bigint): Promise<bigint>;
  ggml_backend_register(arg0: bigint): Promise<void>;
  ggml_backend_sched_alloc_graph(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_sched_free(arg0: bigint): Promise<void>;
  ggml_backend_sched_get_backend(arg0: bigint, arg1: number): Promise<bigint>;
  ggml_backend_sched_get_buffer_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_sched_get_buffer_type(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_sched_get_n_backends(arg0: bigint): Promise<number>;
  ggml_backend_sched_get_n_copies(arg0: bigint): Promise<number>;
  ggml_backend_sched_get_n_splits(arg0: bigint): Promise<number>;
  ggml_backend_sched_get_tensor_backend(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_backend_sched_graph_compute(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_sched_graph_compute_async(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_sched_new(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: number, arg5: number): Promise<bigint>;
  ggml_backend_sched_reserve(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_sched_reserve_size(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_backend_sched_reset(arg0: bigint): Promise<void>;
  ggml_backend_sched_set_eval_callback(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_backend_sched_set_tensor_backend(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  ggml_backend_sched_split_graph(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_sched_synchronize(arg0: bigint): Promise<void>;
  ggml_backend_supports_buft(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_supports_op(arg0: bigint, arg1: bigint): Promise<number>;
  ggml_backend_synchronize(arg0: bigint): Promise<void>;
  ggml_backend_tensor_alloc(arg0: bigint, arg1: bigint, arg2: bigint): Promise<number>;
  ggml_backend_tensor_copy(arg0: bigint, arg1: bigint): Promise<void>;
  ggml_backend_tensor_copy_async(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void>;
  ggml_backend_tensor_get(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void>;
  ggml_backend_tensor_get_2d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void>;
  ggml_backend_tensor_get_2d_async(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<void>;
  ggml_backend_tensor_get_async(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void>;
  ggml_backend_tensor_memset(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<void>;
  ggml_backend_tensor_set(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void>;
  ggml_backend_tensor_set_2d(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void>;
  ggml_backend_tensor_set_2d_async(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint): Promise<void>;
  ggml_backend_tensor_set_async(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<void>;
  ggml_backend_unload(arg0: bigint): Promise<void>;
  ggml_backend_view_init(arg0: bigint): Promise<number>;
  ggml_blck_size(arg0: number): Promise<bigint>;
  ggml_get_name(arg0: bigint): Promise<bigint>;
  ggml_is_quantized(arg0: number): Promise<number>;
  ggml_nbytes(arg0: bigint): Promise<bigint>;
  ggml_nelements(arg0: bigint): Promise<bigint>;
  ggml_nrows(arg0: bigint): Promise<bigint>;
  ggml_row_size(arg0: number, arg1: bigint): Promise<bigint>;
  ggml_set_name(arg0: bigint, arg1: bigint): Promise<bigint>;
  ggml_type_name(arg0: number): Promise<bigint>;
  ggml_type_size(arg0: number): Promise<bigint>;
  ggml_validate_row_data(arg0: number, arg1: bigint, arg2: bigint): Promise<number>;
  gguf_add_tensor(arg0: bigint, arg1: bigint): Promise<void>;
  gguf_find_key(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_find_tensor(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_free(arg0: bigint): Promise<void>;
  gguf_get_alignment(arg0: bigint): Promise<bigint>;
  gguf_get_arr_data(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_arr_n(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_arr_str(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  gguf_get_arr_type(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_data_offset(arg0: bigint): Promise<bigint>;
  gguf_get_key(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_kv_type(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_meta_data(arg0: bigint, arg1: bigint): Promise<void>;
  gguf_get_meta_size(arg0: bigint): Promise<bigint>;
  gguf_get_n_kv(arg0: bigint): Promise<bigint>;
  gguf_get_n_tensors(arg0: bigint): Promise<bigint>;
  gguf_get_tensor_name(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_tensor_ne(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_tensor_offset(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_tensor_size(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_tensor_type(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_bool(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_data(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_val_f32(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_f64(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_i16(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_i32(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_i64(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_val_i8(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_str(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_val_u16(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_u32(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_val_u64(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_get_val_u8(arg0: bigint, arg1: bigint): Promise<number>;
  gguf_get_version(arg0: bigint): Promise<number>;
  gguf_init_empty(): Promise<bigint>;
  gguf_init_from_buffer(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  gguf_init_from_callback(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<bigint>;
  gguf_init_from_file(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_init_from_file_ptr(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_remove_key(arg0: bigint, arg1: bigint): Promise<bigint>;
  gguf_set_arr_data(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: bigint): Promise<void>;
  gguf_set_arr_str(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void>;
  gguf_set_kv(arg0: bigint, arg1: bigint): Promise<void>;
  gguf_set_tensor_data(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  gguf_set_tensor_type(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_bool(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_f32(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_f64(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_i16(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_i32(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_i64(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  gguf_set_val_i8(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_str(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  gguf_set_val_u16(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_u32(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_set_val_u64(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  gguf_set_val_u8(arg0: bigint, arg1: bigint, arg2: number): Promise<void>;
  gguf_type_name(arg0: number): Promise<bigint>;
  gguf_write_to_file(arg0: bigint, arg1: bigint, arg2: number): Promise<number>;
  gguf_write_to_file_ptr(arg0: bigint, arg1: bigint, arg2: number): Promise<number>;
  llama_adapter_get_alora_invocation_tokens(arg0: bigint): Promise<bigint>;
  llama_adapter_get_alora_n_invocation_tokens(arg0: bigint): Promise<bigint>;
  llama_adapter_lora_free(arg0: bigint): Promise<void>;
  llama_adapter_lora_init(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_adapter_meta_count(arg0: bigint): Promise<number>;
  llama_adapter_meta_key_by_index(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<number>;
  llama_adapter_meta_val_str(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  llama_adapter_meta_val_str_by_index(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<number>;
  llama_attach_threadpool(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  llama_backend_free(): Promise<void>;
  llama_backend_init(): Promise<void>;
  llama_batch_free(arg0: bigint): Promise<void>;
  llama_batch_get_one(out: bigint, arg0: bigint, arg1: number): Promise<void>;
  llama_batch_init(out: bigint, arg0: number, arg1: number, arg2: number): Promise<void>;
  llama_chat_apply_template(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: bigint, arg5: number): Promise<number>;
  llama_chat_builtin_templates(arg0: bigint, arg1: bigint): Promise<number>;
  llama_context_default_params(out: bigint): Promise<void>;
  llama_decode(arg0: bigint, arg1: bigint): Promise<number>;
  llama_detach_threadpool(arg0: bigint): Promise<void>;
  llama_detokenize(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: number, arg5: number, arg6: number): Promise<number>;
  llama_encode(arg0: bigint, arg1: bigint): Promise<number>;
  llama_flash_attn_type_name(arg0: number): Promise<bigint>;
  llama_free(arg0: bigint): Promise<void>;
  llama_ftype_name(arg0: number): Promise<bigint>;
  llama_get_embeddings(arg0: bigint): Promise<bigint>;
  llama_get_embeddings_ith(arg0: bigint, arg1: number): Promise<bigint>;
  llama_get_embeddings_seq(arg0: bigint, arg1: number): Promise<bigint>;
  llama_get_logits(arg0: bigint): Promise<bigint>;
  llama_get_logits_ith(arg0: bigint, arg1: number): Promise<bigint>;
  llama_get_memory(arg0: bigint): Promise<bigint>;
  llama_get_model(arg0: bigint): Promise<bigint>;
  llama_get_sampled_candidates_count_ith(arg0: bigint, arg1: number): Promise<number>;
  llama_get_sampled_candidates_ith(arg0: bigint, arg1: number): Promise<bigint>;
  llama_get_sampled_logits_count_ith(arg0: bigint, arg1: number): Promise<number>;
  llama_get_sampled_logits_ith(arg0: bigint, arg1: number): Promise<bigint>;
  llama_get_sampled_probs_count_ith(arg0: bigint, arg1: number): Promise<number>;
  llama_get_sampled_probs_ith(arg0: bigint, arg1: number): Promise<bigint>;
  llama_get_sampled_token_ith(arg0: bigint, arg1: number): Promise<number>;
  llama_init_from_model(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_load_mode_from_str(arg0: bigint): Promise<number>;
  llama_load_mode_name(arg0: number): Promise<bigint>;
  llama_log_get(arg0: bigint, arg1: bigint): Promise<void>;
  llama_log_set(arg0: bigint, arg1: bigint): Promise<void>;
  llama_max_devices(): Promise<bigint>;
  llama_max_parallel_sequences(): Promise<bigint>;
  llama_max_tensor_buft_overrides(): Promise<bigint>;
  llama_memory_can_shift(arg0: bigint): Promise<number>;
  llama_memory_clear(arg0: bigint, arg1: number): Promise<void>;
  llama_memory_seq_add(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number): Promise<void>;
  llama_memory_seq_cp(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number): Promise<void>;
  llama_memory_seq_div(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number): Promise<void>;
  llama_memory_seq_keep(arg0: bigint, arg1: number): Promise<void>;
  llama_memory_seq_pos_max(arg0: bigint, arg1: number): Promise<number>;
  llama_memory_seq_pos_min(arg0: bigint, arg1: number): Promise<number>;
  llama_memory_seq_rm(arg0: bigint, arg1: number, arg2: number, arg3: number): Promise<number>;
  llama_model_chat_template(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_model_cls_label(arg0: bigint, arg1: number): Promise<bigint>;
  llama_model_decoder_start_token(arg0: bigint): Promise<number>;
  llama_model_default_params(out: bigint): Promise<void>;
  llama_model_desc(arg0: bigint, arg1: bigint, arg2: bigint): Promise<number>;
  llama_model_free(arg0: bigint): Promise<void>;
  llama_model_ftype(arg0: bigint): Promise<number>;
  llama_model_get_vocab(arg0: bigint): Promise<bigint>;
  llama_model_has_decoder(arg0: bigint): Promise<number>;
  llama_model_has_encoder(arg0: bigint): Promise<number>;
  llama_model_init_from_user(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  llama_model_is_diffusion(arg0: bigint): Promise<number>;
  llama_model_is_hybrid(arg0: bigint): Promise<number>;
  llama_model_is_recurrent(arg0: bigint): Promise<number>;
  llama_model_load_from_file(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_model_load_from_file_ptr(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_model_load_from_splits(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  llama_model_meta_count(arg0: bigint): Promise<number>;
  llama_model_meta_key_by_index(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<number>;
  llama_model_meta_key_str(arg0: number): Promise<bigint>;
  llama_model_meta_val_str(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  llama_model_meta_val_str_by_index(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint): Promise<number>;
  llama_model_n_cls_out(arg0: bigint): Promise<number>;
  llama_model_n_ctx_train(arg0: bigint): Promise<number>;
  llama_model_n_embd(arg0: bigint): Promise<number>;
  llama_model_n_embd_inp(arg0: bigint): Promise<number>;
  llama_model_n_embd_out(arg0: bigint): Promise<number>;
  llama_model_n_head(arg0: bigint): Promise<number>;
  llama_model_n_head_kv(arg0: bigint): Promise<number>;
  llama_model_n_layer(arg0: bigint): Promise<number>;
  llama_model_n_layer_nextn(arg0: bigint): Promise<number>;
  llama_model_n_params(arg0: bigint): Promise<bigint>;
  llama_model_n_swa(arg0: bigint): Promise<number>;
  llama_model_quantize(arg0: bigint, arg1: bigint, arg2: bigint): Promise<number>;
  llama_model_quantize_default_params(out: bigint): Promise<void>;
  llama_model_rope_freq_scale_train(arg0: bigint): Promise<number>;
  llama_model_rope_type(arg0: bigint): Promise<number>;
  llama_model_save_to_file(arg0: bigint, arg1: bigint): Promise<void>;
  llama_model_size(arg0: bigint): Promise<bigint>;
  llama_n_batch(arg0: bigint): Promise<number>;
  llama_n_ctx(arg0: bigint): Promise<number>;
  llama_n_ctx_seq(arg0: bigint): Promise<number>;
  llama_n_rs_seq(arg0: bigint): Promise<number>;
  llama_n_seq_max(arg0: bigint): Promise<number>;
  llama_n_threads(arg0: bigint): Promise<number>;
  llama_n_threads_batch(arg0: bigint): Promise<number>;
  llama_n_ubatch(arg0: bigint): Promise<number>;
  llama_numa_init(arg0: number): Promise<void>;
  llama_opt_epoch(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void>;
  llama_opt_init(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  llama_opt_param_filter_all(arg0: bigint, arg1: bigint): Promise<number>;
  llama_perf_context(out: bigint, arg0: bigint): Promise<void>;
  llama_perf_context_print(arg0: bigint): Promise<void>;
  llama_perf_context_reset(arg0: bigint): Promise<void>;
  llama_perf_sampler(out: bigint, arg0: bigint): Promise<void>;
  llama_perf_sampler_print(arg0: bigint): Promise<void>;
  llama_perf_sampler_reset(arg0: bigint): Promise<void>;
  llama_pooling_type(arg0: bigint): Promise<number>;
  llama_print_system_info(): Promise<bigint>;
  llama_sampler_accept(arg0: bigint, arg1: number): Promise<void>;
  llama_sampler_apply(arg0: bigint, arg1: bigint): Promise<void>;
  llama_sampler_chain_add(arg0: bigint, arg1: bigint): Promise<void>;
  llama_sampler_chain_default_params(out: bigint): Promise<void>;
  llama_sampler_chain_get(arg0: bigint, arg1: number): Promise<bigint>;
  llama_sampler_chain_init(arg0: bigint): Promise<bigint>;
  llama_sampler_chain_n(arg0: bigint): Promise<number>;
  llama_sampler_chain_remove(arg0: bigint, arg1: number): Promise<bigint>;
  llama_sampler_clone(arg0: bigint): Promise<bigint>;
  llama_sampler_copy(arg0: bigint, arg1: bigint): Promise<void>;
  llama_sampler_free(arg0: bigint): Promise<void>;
  llama_sampler_get_seed(arg0: bigint): Promise<number>;
  llama_sampler_init(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_sampler_init_adaptive_p(arg0: number, arg1: number, arg2: number): Promise<bigint>;
  llama_sampler_init_dist(arg0: number): Promise<bigint>;
  llama_sampler_init_dry(arg0: bigint, arg1: number, arg2: number, arg3: number, arg4: number, arg5: bigint, arg6: bigint): Promise<bigint>;
  llama_sampler_init_grammar(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  llama_sampler_init_grammar_lazy_patterns(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<bigint>;
  llama_sampler_init_greedy(): Promise<bigint>;
  llama_sampler_init_infill(arg0: bigint): Promise<bigint>;
  llama_sampler_init_logit_bias(arg0: number, arg1: number, arg2: bigint): Promise<bigint>;
  llama_sampler_init_min_p(arg0: number, arg1: bigint): Promise<bigint>;
  llama_sampler_init_mirostat(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): Promise<bigint>;
  llama_sampler_init_mirostat_v2(arg0: number, arg1: number, arg2: number): Promise<bigint>;
  llama_sampler_init_penalties(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): Promise<bigint>;
  llama_sampler_init_temp(arg0: number): Promise<bigint>;
  llama_sampler_init_temp_ext(arg0: number, arg1: number, arg2: number): Promise<bigint>;
  llama_sampler_init_top_k(arg0: number): Promise<bigint>;
  llama_sampler_init_top_n_sigma(arg0: number): Promise<bigint>;
  llama_sampler_init_top_p(arg0: number, arg1: bigint): Promise<bigint>;
  llama_sampler_init_typical(arg0: number, arg1: bigint): Promise<bigint>;
  llama_sampler_init_xtc(arg0: number, arg1: number, arg2: bigint, arg3: number): Promise<bigint>;
  llama_sampler_name(arg0: bigint): Promise<bigint>;
  llama_sampler_reset(arg0: bigint): Promise<void>;
  llama_sampler_sample(arg0: bigint, arg1: bigint, arg2: number): Promise<number>;
  llama_set_abort_callback(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void>;
  llama_set_adapter_cvec(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number): Promise<number>;
  llama_set_adapters_lora(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  llama_set_causal_attn(arg0: bigint, arg1: number): Promise<void>;
  llama_set_embeddings(arg0: bigint, arg1: number): Promise<void>;
  llama_set_n_threads(arg0: bigint, arg1: number, arg2: number): Promise<void>;
  llama_set_sampler(arg0: bigint, arg1: number, arg2: bigint): Promise<number>;
  llama_split_path(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<number>;
  llama_split_prefix(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<number>;
  llama_state_get_data(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  llama_state_get_size(arg0: bigint): Promise<bigint>;
  llama_state_load_file(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<number>;
  llama_state_save_file(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  llama_state_seq_get_data(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint>;
  llama_state_seq_get_data_ext(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  llama_state_seq_get_size(arg0: bigint, arg1: number): Promise<bigint>;
  llama_state_seq_get_size_ext(arg0: bigint, arg1: number, arg2: number): Promise<bigint>;
  llama_state_seq_load_file(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: bigint, arg5: bigint): Promise<bigint>;
  llama_state_seq_save_file(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: bigint): Promise<bigint>;
  llama_state_seq_set_data(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<bigint>;
  llama_state_seq_set_data_ext(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number): Promise<bigint>;
  llama_state_set_data(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  llama_supports_gpu_offload(): Promise<number>;
  llama_supports_mlock(): Promise<number>;
  llama_supports_mmap(): Promise<number>;
  llama_supports_rpc(): Promise<number>;
  llama_synchronize(arg0: bigint): Promise<void>;
  llama_time_us(): Promise<bigint>;
  llama_token_to_piece(arg0: bigint, arg1: number, arg2: bigint, arg3: number, arg4: number, arg5: number): Promise<number>;
  llama_tokenize(arg0: bigint, arg1: bigint, arg2: number, arg3: bigint, arg4: number, arg5: number, arg6: number): Promise<number>;
  llama_version(): Promise<bigint>;
  llama_vocab_bos(arg0: bigint): Promise<number>;
  llama_vocab_eos(arg0: bigint): Promise<number>;
  llama_vocab_eot(arg0: bigint): Promise<number>;
  llama_vocab_fim_mid(arg0: bigint): Promise<number>;
  llama_vocab_fim_pad(arg0: bigint): Promise<number>;
  llama_vocab_fim_pre(arg0: bigint): Promise<number>;
  llama_vocab_fim_rep(arg0: bigint): Promise<number>;
  llama_vocab_fim_sep(arg0: bigint): Promise<number>;
  llama_vocab_fim_suf(arg0: bigint): Promise<number>;
  llama_vocab_get_add_bos(arg0: bigint): Promise<number>;
  llama_vocab_get_add_eos(arg0: bigint): Promise<number>;
  llama_vocab_get_add_sep(arg0: bigint): Promise<number>;
  llama_vocab_get_attr(arg0: bigint, arg1: number): Promise<number>;
  llama_vocab_get_score(arg0: bigint, arg1: number): Promise<number>;
  llama_vocab_get_suppress_tokens(arg0: bigint, arg1: bigint): Promise<bigint>;
  llama_vocab_get_text(arg0: bigint, arg1: number): Promise<bigint>;
  llama_vocab_is_control(arg0: bigint, arg1: number): Promise<number>;
  llama_vocab_is_eog(arg0: bigint, arg1: number): Promise<number>;
  llama_vocab_mask(arg0: bigint): Promise<number>;
  llama_vocab_n_tokens(arg0: bigint): Promise<number>;
  llama_vocab_nl(arg0: bigint): Promise<number>;
  llama_vocab_pad(arg0: bigint): Promise<number>;
  llama_vocab_sep(arg0: bigint): Promise<number>;
  llama_vocab_type(arg0: bigint): Promise<number>;
  mtmd_batch_add_chunk(arg0: bigint, arg1: bigint): Promise<number>;
  mtmd_batch_encode(arg0: bigint): Promise<number>;
  mtmd_batch_free(arg0: bigint): Promise<void>;
  mtmd_batch_get_output_embd(arg0: bigint, arg1: bigint): Promise<bigint>;
  mtmd_batch_init(arg0: bigint): Promise<bigint>;
  mtmd_bitmap_free(arg0: bigint): Promise<void>;
  mtmd_bitmap_get_data(arg0: bigint): Promise<bigint>;
  mtmd_bitmap_get_id(arg0: bigint): Promise<bigint>;
  mtmd_bitmap_get_n_bytes(arg0: bigint): Promise<bigint>;
  mtmd_bitmap_get_nx(arg0: bigint): Promise<number>;
  mtmd_bitmap_get_ny(arg0: bigint): Promise<number>;
  mtmd_bitmap_init(arg0: number, arg1: number, arg2: bigint): Promise<bigint>;
  mtmd_bitmap_init_from_audio(arg0: bigint, arg1: bigint): Promise<bigint>;
  mtmd_bitmap_init_lazy(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<bigint>;
  mtmd_bitmap_is_audio(arg0: bigint): Promise<number>;
  mtmd_bitmap_set_id(arg0: bigint, arg1: bigint): Promise<void>;
  mtmd_bitmap_set_mergeable(arg0: bigint, arg1: number): Promise<void>;
  mtmd_context_params_default(out: bigint): Promise<void>;
  mtmd_decode_use_mrope(arg0: bigint): Promise<number>;
  mtmd_decode_use_non_causal(arg0: bigint, arg1: bigint): Promise<number>;
  mtmd_default_marker(): Promise<bigint>;
  mtmd_encode_chunk(arg0: bigint, arg1: bigint): Promise<number>;
  mtmd_free(arg0: bigint): Promise<void>;
  mtmd_gen_audio_get_info(out: bigint, arg0: bigint): Promise<void>;
  mtmd_gen_audio_process(arg0: bigint, arg1: bigint, arg2: bigint): Promise<number>;
  mtmd_gen_inp_default(out: bigint, arg0: bigint): Promise<void>;
  mtmd_get_audio_sample_rate(arg0: bigint): Promise<number>;
  mtmd_get_cap_from_file(out: bigint, arg0: bigint): Promise<void>;
  mtmd_get_marker(arg0: bigint): Promise<bigint>;
  mtmd_get_output_embd(arg0: bigint): Promise<bigint>;
  mtmd_helper_bitmap_init_from_buf(out: bigint, arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: bigint): Promise<void>;
  mtmd_helper_bitmap_init_from_file(out: bigint, arg0: bigint, arg1: bigint, arg2: number, arg3: bigint): Promise<void>;
  mtmd_helper_decode_image_chunk(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number, arg5: number, arg6: number, arg7: bigint, arg8: bigint, arg9: bigint): Promise<number>;
  mtmd_helper_eval_chunk_single(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: number, arg7: bigint): Promise<number>;
  mtmd_helper_eval_chunks(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number, arg4: number, arg5: number, arg6: number, arg7: bigint): Promise<number>;
  mtmd_helper_gen_audio_free(arg0: bigint): Promise<void>;
  mtmd_helper_gen_audio_get_output(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<number>;
  mtmd_helper_gen_audio_init(arg0: bigint, arg1: bigint): Promise<bigint>;
  mtmd_helper_gen_audio_reset(arg0: bigint): Promise<void>;
  mtmd_helper_gen_audio_set_input(arg0: bigint, arg1: bigint): Promise<number>;
  mtmd_helper_gen_audio_step_gen(arg0: bigint, arg1: number, arg2: bigint, arg3: bigint, arg4: bigint): Promise<number>;
  mtmd_helper_gen_audio_step_prompt(arg0: bigint, arg1: number): Promise<number>;
  mtmd_helper_get_n_pos(arg0: bigint): Promise<number>;
  mtmd_helper_get_n_tokens(arg0: bigint): Promise<bigint>;
  mtmd_helper_image_get_decoder_pos(arg0: bigint, arg1: number, arg2: bigint): Promise<void>;
  mtmd_helper_init_opt_default(out: bigint): Promise<void>;
  mtmd_helper_log_set(arg0: bigint, arg1: bigint): Promise<void>;
  mtmd_helper_model_can_chat(arg0: bigint, arg1: bigint): Promise<number>;
  mtmd_helper_support_video(arg0: bigint): Promise<number>;
  mtmd_helper_video_init_params_default(out: bigint): Promise<void>;
  mtmd_image_tokens_get_decoder_pos(out: bigint, arg0: bigint, arg1: number, arg2: bigint): Promise<void>;
  mtmd_image_tokens_get_id(arg0: bigint): Promise<bigint>;
  mtmd_image_tokens_get_n_pos(arg0: bigint): Promise<number>;
  mtmd_image_tokens_get_n_tokens(arg0: bigint): Promise<bigint>;
  mtmd_init_from_file(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint>;
  mtmd_input_chunk_copy(arg0: bigint): Promise<bigint>;
  mtmd_input_chunk_free(arg0: bigint): Promise<void>;
  mtmd_input_chunk_get_id(arg0: bigint): Promise<bigint>;
  mtmd_input_chunk_get_n_pos(arg0: bigint): Promise<number>;
  mtmd_input_chunk_get_n_tokens(arg0: bigint): Promise<bigint>;
  mtmd_input_chunk_get_placeholder(arg0: bigint): Promise<bigint>;
  mtmd_input_chunk_get_tokens_image(arg0: bigint): Promise<bigint>;
  mtmd_input_chunk_get_tokens_text(arg0: bigint, arg1: bigint): Promise<bigint>;
  mtmd_input_chunk_get_type(arg0: bigint): Promise<number>;
  mtmd_input_chunk_load(arg0: bigint, arg1: bigint): Promise<bigint>;
  mtmd_input_chunk_save(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<number>;
  mtmd_input_chunks_free(arg0: bigint): Promise<void>;
  mtmd_input_chunks_get(arg0: bigint, arg1: bigint): Promise<bigint>;
  mtmd_input_chunks_init(): Promise<bigint>;
  mtmd_input_chunks_size(arg0: bigint): Promise<bigint>;
  mtmd_log_set(arg0: bigint, arg1: bigint): Promise<void>;
  mtmd_support_audio(arg0: bigint): Promise<number>;
  mtmd_support_vision(arg0: bigint): Promise<number>;
  mtmd_test_create_input_chunks(): Promise<bigint>;
  mtmd_tokenize(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint): Promise<number>;
  mtmd_tokenize_from_parts(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number): Promise<number>;
}
